# Projectile Motion Simulator

## Goals - Phase 1:
   1. Simulate motion using kinematic equations
   2. Display motion using vectors or an animation
   3. Accept user input to change motion variables

## Goals - Phase 2:
   1. Implement drag coefficients
   2. Compare ideal case vs. case with drag

## Equations:
   - Free-Fall Acceleration: 1/2gt^2

   - Vector Components:
     - Vx0 = V0 * cos(theta)
     - Vy0 = V0 * sin(theta)
     - V = sqrt(vx^2 + vy^2)

   - Kinematic Equations (no drag):
     - X(t) = X0 + Vx0t <- no drag
     - Y(t) = Y0 + Vy0t - 1/2gt^2
     - Vx(t) = Vx0 <- no drag
     - Vy(t) = Vy0 - gt

### Adding Drag:
    To add drag we will need to convert the kinematic equations from linear into rates of change using calculus
    for example to find the x-component for velocity, the change in x over the change in time = vx (dx/dt = vx)

    We will have to use Euler's method to perform numerical integration for each timestep

In [1]:
import matplotlib.pyplot as plt
import numpy as np

# Tools:

This project will rely on numpy for computation and matplotlib for visuals

## Numpy:

   - Initializing arrays: a = np.array([])
   - Accessing array indices: a[1]
   - Slicing: a[:3], accesses the first 3 elements
      Slice indexing of a list copies the elements into a new list,
      slicing an array returns a view: an object that refers to data in the original
      array. The original array can be mutated using the view


In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
print(f"Original Array {a}")
b = a[3:]
print(f"Sliced Array: {b}")
b[0] = 40 # <== changes value of original array (a)
print(f"Modified Original Array: {a}")

Original Array [1 2 3 4 5 6]
Sliced Array: [4 5 6]
Modified Original Array: [ 1  2  3 40  5  6]


## Higher Dimension Arrays:
- Initializing higher-dimension arrays: np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
- This initializes a 2D array, you can tell it's 2d by the number of [], which is 2 on either side
- Array.ndim to determine the dimensions of an array
- To access elements in a 2D array, use the syntax array[row, column] (row = 2nd to last, column = last)
- Use .shape to view a tuple of integers that specify the number of elements in each dimension
- Use .size to view the number of elements in an array
- Use .dtype to view the datatype of the array


In [11]:
c = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(f"Array: {c}")
print(f"Dimensions: {c.ndim}")
print(f"Shape: {c.shape}")
print(f"Fourth element of third row: {c[2,3]}")


Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimensions: 2
Shape: (3, 4)
Fourth element of third row: 12


## Basic Arrays:

- Use .zeros(i) for an array of zeros with i elements
- Use .arange(i) for an array starting at zero up to i elements
- Or .arange(start, stop, step) for an array with evenly spaced intervals
- Use .linspace(start, end, num=interval) for an array with values spaced linearly
- use dtype= as a parameter to specify which datatype the array should be

## Manipulating Elements:

- .sort() to sort in an ascending order
- .searchsorted() to find elements in a sorted array
- .partition() to do a partial sort
- .concatenate() to concatenate arrays into a continuous one
- use axis= parameter to concatinate across a different axis

In [27]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])